### PR TITLE
TypeScript declaration files

### PR DESCRIPTION
**Pull request by twobit**
Added TS declaration file generation.

### CODE REVIEW

**Comment by reedspool** [comment]
Hello, I'm using this library via the NPM package, and it appears that these declaration files aren't present in my node_modules directory. Is it possible these changes weren't deployed to NPM?

**Comment by vogtb** [comment]
It's possible, and I'd say it's even probable. I've not logged into npm since I initially published this library, and it's not actively maintained, so I think it's out of date.

**Comment by reedspool** [comment]
No problem at all, thanks! We just downloaded the `dist` and used it directly instead of the npm package. And the declaration files are working great there :) Will share our little project if you're interested!

**Comment by reedspool** [comment]
Here's the project https://github.com/kangp3/hypersheets

**Pull request merged**
